# Input Method (0: Telex, 1: VNI, 2: Simple Telex, 3: VIQR)
InputMethod=Telex
# Output Charset (0: Unicode)
OutputCharset=Unicode
# Auto restore keys with invalid word
AutoNonVnRestore=True
# Process W at word begin
ProcessWAtWordBegin=True
